### ISSUE TITLE
ChangelogGenerator as a NuGet Tool

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Entropy#32]
Migrate `ChangelogGenerator` to a [NuGet tool](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)

Benefits
- Run the tool from anywhere in the path

**Comment by nkolev92** [comment]
Done: https://github.com/NuGet/Entropy/tree/main/NuGetReleaseTool/NuGetReleaseTool/GenerateInsertionChangelogCommand
